[entryPoints]
  [entryPoints.http]
    address = ":80"
[web]
address = ":8081"
[mesos]
endpoint = "zk://leader.mesos:2181/mesos"
watch = true
domain = "mesos.localhost"
exposedByDefault = false
filename = "/mesos.tmpl"
templateVersion = 2
[mesos.TLS]
insecureSkipVerify = true
zkDetectionTimeout = 30
refreshSeconds = 30
ipSources = "netinfo,mesos,docker,host"
stateTimeoutSecond = "30"
groupsAsSubDomains = true
